### ISSUE TITLE
How Can i implement this in React JS ?

### ISSUE THREAD

**Issue by RajuProgmattic** [Joel2B/Custom-Video-Player#2]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Joel2B** [comment]
you can use this guide to use it
https://docs.fluidplayer.com/docs/integration/react/

since i don't have it uploaded to npm, you have to include it externally
https://appsdev.cyou/player/v1/current/player.min.js

you can use the `componentDidMount` method to attach the script to your component

```js
componentDidMount() {
    const script = document.createElement('script');
    script.src = 'https://appsdev.cyou/player/v1/current/player.min.js';
    script.async = true;

    document.body.appendChild(script);
}
```

or with useEffect

```js
useEffect(() => {
    const script = document.createElement('script');
    script.src = 'https://appsdev.cyou/player/v1/current/player.min.js';
    script.async = true;

    document.body.appendChild(script);

    return () => {
        document.body.removeChild(script);
    };
}, []);
```

https://betterprogramming.pub/4-ways-of-adding-external-js-files-in-reactjs-823f85de3668

any other question just say so

**Comment by RajuProgmattic** [comment]
import React, { useEffect, useState, useRef } from 'react';
import skipad from './skipad.xml';
import noskipad from './noskipad.xml';
import fluidPlayer from 'fluid-player';
import {appendScript} from './script';

import "fluid-player/src/css/fluidplayer.css";


const Player = () => {
    
    useEffect(() => {
        appendScript('https://appsdev.cyou/player/v1/current/player.min.js')
    }, [])
    return (
        <>

            <div className='container-fluid' style={{ paddingTop: '10%' }}>
                <div className='row'>
                    <div className='col-12'>
                        <video id='fluid-player-e2e-case' width='100%' height='300px'>
                            <source src='https://cdnurl.moviflex.in/video-data/kaand/master.m3u8'

                                type='application/x-mpegURL'
                            />
                        </video>
                     

                    </div>
                </div>
            </div>


        </>
    )
}


export default Player;



and my script file 
export const appendScript = (scriptToAppend) => {
    const script = document.createElement("script");
    script.src = scriptToAppend;
    script.async = true;
    document.body.appendChild(script);
}

How can i use after that plz suggest me in my Player Component

**Comment by Joel2B** [comment]
this worked for me, i think there are better ways to do this

**player.js**
```js
import React, { useEffect } from 'react';
import appendScript from './appendScript';
import config from './config';

const Player = () => {
    let self = React.createRef();
    let player = null;

    const url = 'https://appsdev.cyou/player/v1/current/player.min.js';

    const setup = () => {
        player = window.fluidPlayer(self.current, config);
    };

    useEffect(() => {
        appendScript(url).then(setup);

        return () => {
            if (player) {
                player.destroy();
            }
        };
    }, []);

    return (
        <video ref={self}>
            <source src="https://cdnurl.moviflex.in/video-data/kaand/master.m3u8" type="application/x-mpegurl" />
        </video>
    );
};

export default Player;
```

**appendScript.js**
```js
const appendScript = (url) => {
    return new Promise((resolve) => {
        const tag = document.createElement('script');
        tag.async = false;
        tag.src = url;

        document.body.appendChild(tag);

        tag.addEventListener('load', resolve, {
            once: true,
        });
    });
};

export default appendScript;
```

**config.js**
```js
const config = {
    layoutControls: {
        fillToContainer: true,
        autoPlay: {
            waitInteraction: true,
        },
        playButtonShowing: true,
        playPauseAnimation: true,
        controlBar: {
            autoHide: true,
            autoHideTimeout: 3,
            animated: true,
        },
        menu: {
            audio: true,
            subtitles: true,
        },
        fullscreen: {
            iosNative: true,
        },
    },
    hls: {
        overrideNative: true,
    },
    debug: true,
};

export default config;
```

**Comment by Joel2B** [comment]
anything else, create other issue
