### ISSUE TITLE
How to install

### ISSUE THREAD

**Issue by khldb** [Joel2B/Custom-Video-Player#4]
Thanks for this beautiful player
It's a great job you did.

Unfortunately
I do not know how to install on the hosting of my site.. cpanel shared hosting ..
How do I generate a link like this.  `https://appsdev.cyou/player/v1/current/player.min.js`
It is hosted on my website hosting.

I don't know what it is and how npm works
Can I upload the entire video player file to my site
But how do I create a javascript link to the video player.
I don't know the correct way
I searched for several months but did not know how it works.

thank you so much for your help i really appreciate it .

**Comment by Joel2B** [comment]
to build this project and get the player.min.js, follow this:

first you need to install the latest version of nodejs

the easy way to install is to download it from the nodejs official website

> https://nodejs.org/es/

download the "LTS" version

the other way is to use a manager that allows you to install multiple nodejs versions
> https://github.com/nvm-sh/nvm

once installed, check in your console, if the installation was successful,
using `node -v` and `npm -v`

![image](https://user-images.githubusercontent.com/58922368/169720203-293a44a6-9b62-4a66-a75d-085a25357f8b.png)

then you clone the project, there are several ways, from the web by .zip or by git
> https://git-scm.com/

then open a new console and go to the project location 
and from there run `npm install`

then if the packages are installed correctly, run `npm run build-dev`

if everything went well, in the `dist` location, 
you will see several html files and player.min.js

![image](https://user-images.githubusercontent.com/58922368/169720446-71d50862-0e27-4ebe-8563-40b8c2382f81.png)

now, if you want to use this player.min.js in only one web page, 
just run `npm run build`

copy `dist` content to your website, 
you will have to copy the files everywhere you want to use the player

![image](https://user-images.githubusercontent.com/58922368/169720468-672bdb2a-cbf7-4a96-a345-f0f534f9e850.png)

if you only want to be on a single site and be used by several web pages, 
run `npm run build-cdn`

this will generate several files in `dist-cdn`

![image](https://user-images.githubusercontent.com/58922368/169720484-5b89f77b-7e23-4670-b1d7-6e27a224b5aa.png)

copy the entire `v1` folder to your main web page 
and now you can use it wherever you want

by default is assigned the path `https://appsdev.cyou/player`,
so just swap it for yours, `https://{YOUR_DOMAIN}/player`
in the [desploy.json](../blob/master/deploy.json) file

run again npm `run build-cdn`

in the hosting, create the `player` folder 
and copy the whole `v1` folder (including the same folder) to your hosting

and your script would look like this

```html
<script src="https://{YOUR_DOMAIN}/player/v1/current/player.min.js"></script>
```

any other questions, let me know

**Comment by khldb** [comment]
Excuse me for being a beginner
So this question came to my mind
Why should the script be configured with nodejs
Why not upload script files directly to the site?
I don't understand why exactly this way.

The important ...
It seems that the program does not work on Windows 7.
So I downloaded an older version of the program. v14.0.0 (node-v14.0.0-x64.msi 

![New Bitmap Image (2)](https://user-images.githubusercontent.com/12476388/169780179-2a1ebca4-1c11-4716-8e0a-be8993aab38d.jpg)

![2](https://user-images.githubusercontent.com/12476388/169780857-7f4b7e68-ceaf-43e3-b5fc-1f23e5e460f0.jpg)


Do I need to download the latest version of nodejs?

**Comment by Joel2B** [comment]
nodejs is used to facilitate several jobs when building the final player.min.js file,
such as joining all the separate modules you see in src, translating the code to one that all browsers can understand.

you entered the nodejs interface, exit by typing `.exit`
and in the windows console, execute all the commands mentioned above.

the version you use also works.

![image](https://user-images.githubusercontent.com/58922368/169857706-b3a9cc12-40ee-4bf1-bafd-8eaa3219f061.png)

**Comment by khldb** [comment]
i beg your pardon .I want you to explain in more detail.
windows console its cmd.exe .. right ?

download this to my computer 
https://github.com/Joel2B/Custom-Video-Player/archive/refs/heads/master.zip 
whats mean  project location.. 
something like this 
K:\folder\Custom-Video-Player-master.zip npm install

What exactly do I type in cmd?

I'm stuck on the first step

**Comment by Joel2B** [comment]
right, with cmd.exe

download and extract the [master.zip](https://github.com/Joel2B/Custom-Video-Player/archive/refs/heads/master.zip) file with WinRAR, 
or any other program that allows you to decompress rar files.

Copy the folder location and in your cmd, 

![image](https://user-images.githubusercontent.com/58922368/170390729-2ba88005-7996-458a-a42f-63de763ae8d0.png)

type `cd \d ` and then paste the location, will look like this

`cd \d K:\folder\Custom-Video-Player-master`

press enter, and then type `npm install`

![image](https://user-images.githubusercontent.com/58922368/170391182-39cabab2-6f3f-4fe0-875f-3cb224a8cddf.png)

don't worry, if still is not clear, keep writing to me

**Comment by khldb** [comment]
I finally did it .

I uploaded these files from K:\Custom-Video-Player\dist-cdn\v1\current 
 to my site .

![169720484-5b89f77b-7e23-4670-b1d7-6e27a224b5aa](https://user-images.githubusercontent.com/12476388/170528222-0c1d3127-cdd1-4142-948c-e85d7c46030c.png)

Do I have to upload the other files that appeared in the dist file to my site?

I mean these files
![169720446-71d50862-0e27-4ebe-8563-40b8c2382f81](https://user-images.githubusercontent.com/12476388/170529342-00f5d46f-8708-495d-a0ac-7082642a5f81.png)

**Comment by khldb** [comment]
I only uploaded these 3 files to my site .
![170528222-0c1d3127-cdd1-4142-948c-e85d7c46030c](https://user-images.githubusercontent.com/12476388/170774150-03c8789f-c8e2-4901-94fe-6c8d137e5dc9.png)

<script src="https://{MY_DOMAIN}/player/v1/current/player.min.js"></script>

Now the video player is working .

I'm just wondering what is the difference between the player.min.js script file produced by nodejs .
And your `https://appsdev.cyou/player/v1/current/player.min.js` script file that I can downloaded and upload to my site.

Especially I just changed this "cdn": "https://appsdev.cyou/player" in deploy.json .

thank you so much

**Comment by Joel2B** [comment]
If you download the player.min.js from appsdev.cyou, and upload it to your website,
will point all resources as images to the appsdev.cyou domain.

then to avoid that you change the domain, as you said, in deploy.json,
and now that nodejs player.min.js will point to the domain you specified,
and you can upload it to a primary website, and use it on any website.

the advantage of building your own build, is that you will not depend on appsdev.cyou,
in case that stops working, you will have the player.min.js on your web page,

the disadvantage is that when i make changes to the source code,
you will have to do `git pull`, `npm run build-cdn`, upload it back to your site
to apply the latest changes to all your websites.
