### ISSUE TITLE
VAST AD

### ISSUE THREAD

**Issue by rajukumar1995** [Joel2B/Custom-Video-Player#5]
i am using vast ad feature in Your player .i want call api on every ad play .how can i do that plz explain .i am using reactjs

**Comment by Joel2B** [comment]
when you create an instance of the player, 
send the following configuration

```js
const config = {
  vastOptions: {
    vastAdvanced: {
      vastPlayCallback: () => {
        console.warn('call api');
      },
    },
  },
};

const player = fluidPlayer('player', config);
```
