### ISSUE TITLE
in mobile view player quality switcher not showing in mobile .

### ISSUE THREAD

**Issue by rajukumar1995** [Joel2B/Custom-Video-Player#6]
A clear and concise description of what the problem is.

**Additional context**
Add any other context or screenshots about the request here.

**Comment by Joel2B** [comment]
the cases for you to see the quality switcher are:

1. have 2 or more video sources within the video tag
e.g. [vod_basic](https://github.com/Joel2B/Custom-Video-Player/blob/master/test/html/vod_basic.tpl.html)

2. have a playlist of type m3u8 or mpd
e.g. [hls_vod](https://github.com/Joel2B/Custom-Video-Player/blob/master/test/html/hls_vod.tpl.html)

to help you better you can send me the code that you are using
