### ISSUE TITLE
Mobile View player control Panel

### ISSUE THREAD

**Issue by rajukumar1995** [Joel2B/Custom-Video-Player#7]
i have an issue in mobile view. I want the web view control panel show in mobile view. how can I implement this ?

**Comment by Joel2B** [comment]
in the line

https://github.com/Joel2B/Custom-Video-Player/blob/master/src/js/player.js#L61

```js
// Mobile device
this.mobile = (IS_ANDROID && this.touch) || IS_IOS;
```

change it to 

```js
// Mobile device
this.mobile = false;
```

this will display the web design no matter if is mobile or not,
all functions should work without problems
