### ISSUE TITLE
Preload "none" ignored with  HLS

### ISSUE THREAD

**Issue by forumwt** [Joel2B/Custom-Video-Player#8]
Whether I set preload="none" or  preload: false or  preload:'none, the video is loaded before user press play button. 
I'm talk about HLS files.

I have read HLS documentation and find solution to stop preload files

```
       hls: {
            overrideNative: true, 
            config: (options) => ({
            autoStartLoad: false
        }) 
```

But in that case after clicking on play button video does not start, any solution to stop preloading files before user click on play button?

**Comment by Joel2B** [comment]
follow this to do what you want to do
https://github.com/video-dev/hls.js/issues/1256

i made a commit, seems to work.
https://github.com/Joel2B/Custom-Video-Player/commit/28fc4181fb2042dd4416ec9a394b755814d90321
